#docker-compose exec postgre_dev /bin/bash
version: "3"
services:
  postgre_dev:
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      LANG: ${LANG}
    env_file:
      - .env
    ports:
      - 15432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
#      - ./sqls:/docker-entrypoint-initdb.d
#      - ./conf/postgresql.conf:/etc/postgresql.conf
volumes:
  postgre_dev:
    driver: local
