version: "3"
services:
  gitbucket:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
      - 29418:29418
    volumes:
      - ./data:/gitbucket
    restart: always
