version: "3"
services:
  redmine:
    container_name: ${REDMINE_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./redmine/docker/Dockerfile
    ports:
      - "33000:3000"
    volumes:
      - ./redmine/docker/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./redmine/files:/usr/src/redmine/files
      - ./redmine/log:/usr/src/redmine/log
      - ./redmine/plugins:/usr/src/redmine/plugins
      - ./redmine/public/themes:/usr/src/redmine/public/themes
    restart: always
    environment:
      REDMINE_DB_POSTGRES: ${REDMINE_DB_POSTGRES}
      REDMINE_DB_DATABASE: ${REDMINE_DB_DATABASE}
      REDMINE_DB_USERNAME: ${REDMINE_DB_USERNAME}
      REDMINE_DB_PASSWORD: ${REDMINE_DB_PASSWORD}
      TZ: ${TIME_ZONE}
    depends_on:
      - postgres
    networks:
      - my_network
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./postgres/docker/Dockerfile
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      # - ./postgres/sqls:/docker-entrypoint-initdb.d
      # - ./postgres/conf/postgresql.conf:/etc/postgresql.conf
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DB}
      TZ: ${TIME_ZONE}
    networks:
      - my_network
  mailhog:
    container_name: ${MAIL_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./mail/docker/Dockerfile
    ports:
      - "8025:8025"
      - "11025:1025"
    depends_on:
      - redmine
    networks:
      - my_network
networks:
  my_network: