version: "3"
services:
  gitlab:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - "8888:80"
      - "1022:22"
    volumes:
      - "./config:/etc/gitlab"
      - "./logs:/var/log/gitlab"
      - "./data:/var/opt/gitlab"
