version: "3"
services:
  jenkins:
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8889:8080"
      - "5000:5000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
