version: "3"
services:
  mysql_dev:
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TIME_ZONE}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 13306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./sqls:/docker-entrypoint-initdb.d
    tty: true
